#!/usr/bin/env bash
# USAGE: ./new FILENAME_STEM

filename="${1%.*}"
filename="${filename##*/}"
filename="$(date +"%F")-${filename}"

read -p 'Title: ' title

csplit -s src/index.md 8
echo "- $(date +"%d %b %Y") - [${title}](${filename}.html)" >> xx00
cat xx00 xx01 > src/index.md
rm xx00 xx01

echo "[<-- Back to Main Page](index.html)" >> "src/${filename}.md"
echo >> "src/${filename}.md"
echo "# ${title}" >> "src/${filename}.md"
echo "*$(date +"%d %b %Y")*" >> "src/${filename}.md"
echo >> "src/${filename}.md"
echo >> "src/${filename}.md"

vim "src/${filename}.md"
